#!/bin/sh

umask 077

base="$HOME/.fftoken"
mkdir -p $base

access_token_url='http://fanfou.com/oauth/access_token'

consumer_tmp=$(mktemp -t curlicue_consumer.XXXXXX)
request_token_tmp=$(mktemp -t curlicue_request_token.XXXXXX)
access_token_tmp=$(mktemp -t curlicue_access_token.XXXXXX)

read -p 'Consumer key: ' key
read -p 'Consumer secret: ' secret

read -p "Fanfou loginname(ID/Mobile Number/Email): " name
stty -echo
read -p "Fanfou Password: " password ; echo
stty echo

output_file="$base/$name.token"
echo "oauth_consumer_key=$(curlicue -u "$key")&oauth_consumer_secret=$(
    curlicue -u "$secret")" > $consumer_tmp

curlicue -f $consumer_tmp -p "x_auth_username=$name&x_auth_password=$password&x_auth_mode=client_auth" $access_token_url > $access_token_tmp
paste -d '&' $consumer_tmp $access_token_tmp > "$output_file"
echo
echo "OK! Now you can run: curlicue -f $output_file [-- CURL_OPTS] URL"
